# Generated by Django 2.1.7 on 2019-03-05 05:57

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=500, unique=True)),
                ('title', models.CharField(max_length=2500)),
                ('image_url', models.URLField()),
                ('thumb_url', models.URLField(blank=True, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('place_name_hint', models.CharField(blank=True, max_length=300, null=True)),
                ('geom_hint', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('osm_id', models.CharField(max_length=500, unique=True)),
                ('name', models.CharField(max_length=2500)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.FloatField()),
                ('status', models.IntegerField(choices=[(1, 'new'), (10, 'accepted'), (100, 'rejected')], default=1)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.Photo')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='core.Place')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='selected_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='core.Place'),
        ),
    ]
