# Generated by Django 2.1.7 on 2019-03-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='status',
            field=models.IntegerField(choices=[(1, 'pending'), (2, 'suggested'), (10, 'found'), (100, 'no place name')], default=1),
        ),
    ]
