# Generated by Django 2.1.7 on 2019-05-01 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190310_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='found_at',
            field=models.DateTimeField(null=True),
        ),
    ]
