# Generated by Django 2.1.7 on 2019-05-22 17:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_photo_found_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='exact_geom_radius',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='expected_accuracy',
            field=models.IntegerField(blank=True, choices=[(1, 'exact'), (10, 'entity'), (100, 'broad'), (200, 'no place info')], null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='geom_from_osm',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='photo',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.Country'),
        ),
    ]
